package router

import (
	"net/http"
	"time"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/jmoiron/sqlx"
	"github.com/source-c0de/contacthub/internal/config"
	"github.com/source-c0de/contacthub/internal/handler"
	"github.com/source-c0de/contacthub/internal/middleware"
	"github.com/source-c0de/contacthub/internal/repository"
	"github.com/source-c0de/contacthub/internal/service"

	_ "github.com/source-c0de/contacthub/docs" // This will be auto-generated by swag init
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"go.uber.org/zap"
)

func Setup(
	cfg *config.Config,
	logger *zap.Logger,
	db *sqlx.DB,
) *gin.Engine {

	if cfg.Environment == "production" {
		gin.SetMode(gin.ReleaseMode)
	}

	r := gin.New()

	// CORS
	r.Use(cors.New(cors.Config{
		AllowOrigins:     cfg.AllowedOrigins,
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Content-Type", "Authorization"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
		MaxAge:           12 * time.Hour,
	}))

	// Logger
	r.Use(middleware.Logger(logger))
	r.Use(gin.Recovery())

	// Health Check
	r.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "ok"})
	})

	// Swagger Docs
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Initialize repositories
	userRepo := repository.NewUserRepository(db)
	deptRepo := repository.NewDepartmentRepository(db)
	empRepo := repository.NewEmployeeRepository(db)
	syncRepo := repository.NewSyncRepository(db)
	auditRepo := repository.NewAuditRepository(db)

	// Initialize services
	authSvc := service.NewAuthService(cfg, userRepo)
	deptSvc := service.NewDepartmentService(deptRepo)
	empSvc := service.NewEmployeeService(empRepo)
	syncSvc := service.NewSyncService(syncRepo)
	auditSvc := service.NewAuditService(auditRepo)
	userSvc := service.NewUserService(userRepo)

	// Initialize handlers
	authHandler := handler.NewAuthHandler(authSvc)
	deptHandler := handler.NewDepartmentHandler(deptSvc)
	empHandler := handler.NewEmployeeHandler(empSvc)
	syncHandler := handler.NewSyncHandler(syncSvc)
	auditHandler := handler.NewAuditHandler(auditSvc)
	adminHandler := handler.NewAdminHandler(userSvc)

	// Auth Routes (public)
	auth := r.Group("/api/v1/auth")
	{
		auth.POST("/login", authHandler.Login)
		auth.POST("/logout", authHandler.Logout) // Requires auth in real world but spec says Yes, any
	}

	// Protected Routes (require JWT)
	api := r.Group("/api/v1")
	api.Use(middleware.JWTAuth(cfg, authSvc))
	{
		// Auth user
		api.GET("/auth/me", authHandler.Me)
		api.PUT("/auth/password", authHandler.ChangePassword)

		// Employees
		api.GET("/employees", empHandler.ListEmployees)
		api.GET("/employees/:id", empHandler.GetEmployee)
		// Admin/manager could be enforced by middleware.RequireRole("admin") but using same for now per spec or RBAC middleware
		api.POST("/employees", empHandler.CreateEmployee)
		api.PUT("/employees/:id", empHandler.UpdateEmployee)
		api.DELETE("/employees/:id", empHandler.DeleteEmployee)

		// Departments
		api.GET("/departments", deptHandler.ListDepartments)
		api.POST("/departments", deptHandler.CreateDepartment)
		api.PUT("/departments/:id", deptHandler.UpdateDepartment)
		api.DELETE("/departments/:id", deptHandler.DeleteDepartment)

		// Admin
		adminGroup := api.Group("/admin")
		adminGroup.Use(middleware.RequireRole("admin")) // Requires an RBAC middleware
		{
			adminGroup.GET("/dashboard", adminHandler.GetDashboardStats)
			adminGroup.GET("/users", adminHandler.ListUsers)
			adminGroup.POST("/users/invite", adminHandler.InviteUser)
			adminGroup.PATCH("/users/:id/role", adminHandler.ChangeRole)
			adminGroup.PATCH("/users/:id/deactivate", adminHandler.DeactivateUser)

			// Sync
			adminGroup.GET("/sync/settings", syncHandler.GetSettings)
			adminGroup.PATCH("/sync/settings/:type", syncHandler.ToggleSync)
			adminGroup.POST("/sync/run/:type", syncHandler.RunSync)
			adminGroup.GET("/sync/logs", syncHandler.GetLogs)

			// Audit Logs
			adminGroup.GET("/audit-logs", auditHandler.GetAuditLogs)
			adminGroup.GET("/audit-logs/export", auditHandler.ExportAuditLogs)
		}
	}

	return r
}
